### ISSUE TITLE
[Result] Minimal Todo Without Meta

### ISSUE THREAD

**Issue by omuomugin** [omuomugin/FlowDroid#10]
# Minimal Todo Without Meta

## common
// application
- [x] [method param] com.example.avjindersinghsekhon.minimaltodo.AddToDoActivity - <com.example.avjindersinghsekhon.minimaltodo.AddToDoActivity: java.lang.String formatDate(java.lang.String,java.util.Date)> - 1
- [x] [field] com.example.avjindersinghsekhon.minimaltodo.MainActivity - mToDoItemsArrayList
- [x] [method param] com.example.avjindersinghsekhon.minimaltodo.MainActivity - <com.example.avjindersinghsekhon.minimaltodo.MainActivity: java.util.ArrayList getLocallyStoredData(com.example.avjindersinghsekhon.minimaltodo.StoreRetrieveData)> - 0
- [x] [field] com.example.avjindersinghsekhon.minimaltodo.MainActivity$BasicListAdapter - items
- [x] [method param] com.example.avjindersinghsekhon.minimaltodo.AnalyticsApplication - <com.example.avjindersinghsekhon.minimaltodo.AnalyticsApplication: void send(java.lang.Object,java.lang.String,java.lang.String,java.lang.String)> - 0
- [x] [method param] com.example.avjindersinghsekhon.minimaltodo.AnalyticsApplication - <com.example.avjindersinghsekhon.minimaltodo.AnalyticsApplication: void send(java.lang.Object,java.lang.String,java.lang.String)> - 0
- [x] [method param] com.example.avjindersinghsekhon.minimaltodo.AnalyticsApplication - <com.example.avjindersinghsekhon.minimaltodo.AnalyticsApplication: void send(java.lang.Object)> - 0
- [x] [method param] com.example.avjindersinghsekhon.minimaltodo.StoreRetrieveData - <com.example.avjindersinghsekhon.minimaltodo.StoreRetrieveData: void saveToFile(java.util.ArrayList)> - 0
- [x] [method param] com.example.avjindersinghsekhon.minimaltodo.StoreRetrieveData - <com.example.avjindersinghsekhon.minimaltodo.StoreRetrieveData: org.json.JSONArray toJSONArray(java.util.ArrayList)> - 0
- [x] [field] com.example.avjindersinghsekhon.minimaltodo.DeleteNotificationService - mItem
- [x] [field] com.example.avjindersinghsekhon.minimaltodo.DeleteNotificationService - mToDoItems
- [x] [field] com.example.avjindersinghsekhon.minimaltodo.ToDoItem - mToDoDate
- [x] [method param] com.example.avjindersinghsekhon.minimaltodo.ToDoItem - <com.example.avjindersinghsekhon.minimaltodo.ToDoItem: void setToDoDate(java.util.Date)> - 0
- [x] [field] com.example.avjindersinghsekhon.minimaltodo.ReminderActivity - mItem
- [x] [field] com.example.avjindersinghsekhon.minimaltodo.ReminderActivity - mToDoItems
- [x] [field] com.example.avjindersinghsekhon.minimaltodo.AddToDoActivity - mUserReminderDate

// bug in tool
- [ ] [field] com.example.avjindersinghsekhon.minimaltodo.MainActivity - adapter
- [ ] [field] com.example.avjindersinghsekhon.minimaltodo.ReminderActivity - snoozeOptionsArray
- [ ] [method param] com.example.avjindersinghsekhon.minimaltodo.RecyclerViewEmptySupport - <com.example.avjindersinghsekhon.minimaltodo.RecyclerViewEmptySupport: void setAdapter(android.support.v7.widget.RecyclerView$Adapter)> - 0
- [ ] [field] com.example.avjindersinghsekhon.minimaltodo.ItemTouchHelperClass - adapter

// unknown
- [ ] [method param] com.example.avjindersinghsekhon.minimaltodo.AddToDoActivity - <com.example.avjindersinghsekhon.minimaltodo.AddToDoActivity: android.widget.EditText access$000(com.example.avjindersinghsekhon.minimaltodo.AddToDoActivity)> - 0
- [ ] [method param] com.example.avjindersinghsekhon.minimaltodo.ReminderActivity - <com.example.avjindersinghsekhon.minimaltodo.ReminderActivity: com.example.avjindersinghsekhon.minimaltodo.ToDoItem access$000(com.example.avjindersinghsekhon.minimaltodo.ReminderActivity)> - 0
- [ ] [method param] com.example.avjindersinghsekhon.minimaltodo.ReminderActivity - <com.example.avjindersinghsekhon.minimaltodo.ReminderActivity: void access$400(com.example.avjindersinghsekhon.minimaltodo.ReminderActivity)> - 0
- [ ] [method param] com.example.avjindersinghsekhon.minimaltodo.ReminderActivity - <com.example.avjindersinghsekhon.minimaltodo.ReminderActivity: void access$200(com.example.avjindersinghsekhon.minimaltodo.ReminderActivity)> - 0
- [ ] [method param] com.example.avjindersinghsekhon.minimaltodo.ReminderActivity - <com.example.avjindersinghsekhon.minimaltodo.ReminderActivity: java.util.ArrayList access$100(com.example.avjindersinghsekhon.minimaltodo.ReminderActivity)> - 0
- [ ] [method param] com.example.avjindersinghsekhon.minimaltodo.ReminderActivity - <com.example.avjindersinghsekhon.minimaltodo.ReminderActivity: void access$300(com.example.avjindersinghsekhon.minimaltodo.ReminderActivity)> - 0
- [ ] [method param] com.example.avjindersinghsekhon.minimaltodo.MainActivity - <com.example.avjindersinghsekhon.minimaltodo.MainActivity: com.example.avjindersinghsekhon.minimaltodo.AnalyticsApplication access$000(com.example.avjindersinghsekhon.minimaltodo.MainActivity)> - 0
- [ ] [method param] com.example.avjindersinghsekhon.minimaltodo.AddToDoActivity - <com.example.avjindersinghsekhon.minimaltodo.AddToDoActivity: java.util.Date access$202(com.example.avjindersinghsekhon.minimaltodo.AddToDoActivity,java.util.Date)> - 0
- [ ] [method param] com.example.avjindersinghsekhon.minimaltodo.AddToDoActivity - <com.example.avjindersinghsekhon.minimaltodo.AddToDoActivity: java.util.Date access$202(com.example.avjindersinghsekhon.minimaltodo.AddToDoActivity,java.util.Date)> - 1
- [ ] [method param] com.example.avjindersinghsekhon.minimaltodo.AddToDoActivity - <com.example.avjindersinghsekhon.minimaltodo.AddToDoActivity: boolean access$302(com.example.avjindersinghsekhon.minimaltodo.AddToDoActivity,boolean)> - 0
- [ ] [method param] com.example.avjindersinghsekhon.minimaltodo.AddToDoActivity - <com.example.avjindersinghsekhon.minimaltodo.AddToDoActivity: void access$400(com.example.avjindersinghsekhon.minimaltodo.AddToDoActivity)> - 0

// third party
- [ ] [field] com.nineoldandroids.animation.KeyframeSet - mFirstKeyframe
- [ ] [field] com.nineoldandroids.animation.KeyframeSet - mNumKeyframes
- [ ] [field] com.nineoldandroids.animation.KeyframeSet - mKeyframes
- [ ] [field] com.nineoldandroids.animation.KeyframeSet - mLastKeyframe
- [ ] [field] com.nineoldandroids.animation.Keyframe - mInterpolator
- [ ] [field] com.nineoldandroids.animation.Animator - mListeners
- [ ] [field] com.nineoldandroids.animation.PropertyValuesHolder - mSetter
- [ ] [field] com.nineoldandroids.animation.PropertyValuesHolder - mGetter
- [ ] [field] com.nineoldandroids.animation.PropertyValuesHolder - mKeyframeSet
- [ ] [field] com.nineoldandroids.animation.PropertyValuesHolder$FloatPropertyValuesHolder - mFloatKeyframeSet
- [ ] [field] fr.ganfra.materialspinner.MaterialSpinner$HintAdapter - mContext
- [ ] [field] fr.ganfra.materialspinner.MaterialSpinner - selectorPoints
- [ ] [field] fr.ganfra.materialspinner.MaterialSpinner - arrowColor
- [ ] [field] fr.ganfra.materialspinner.MaterialSpinner - underlineTopSpacing
- [ ] [field] fr.ganfra.materialspinner.MaterialSpinner - errorColor
- [ ] [field] fr.ganfra.materialspinner.MaterialSpinner - floatingLabelColor
- [ ] [field] fr.ganfra.materialspinner.MaterialSpinner - thickness
- [ ] [field] fr.ganfra.materialspinner.MaterialSpinner - error
- [ ] [field] fr.ganfra.materialspinner.MaterialSpinner - innerPaddingTop
- [ ] [field] fr.ganfra.materialspinner.MaterialSpinner - thicknessError
- [ ] [field] fr.ganfra.materialspinner.MaterialSpinner - floatingLabelInsideSpacing
- [ ] [field] fr.ganfra.materialspinner.MaterialSpinner - innerPaddingRight
- [ ] [field] fr.ganfra.materialspinner.MaterialSpinner - alignLabels
- [ ] [field] fr.ganfra.materialspinner.MaterialSpinner - extraPaddingBottom
- [ ] [field] fr.ganfra.materialspinner.MaterialSpinner - currentNbErrorLines
- [ ] [field] fr.ganfra.materialspinner.MaterialSpinner - floatingLabelTopSpacing
- [ ] [field] fr.ganfra.materialspinner.MaterialSpinner - innerPaddingBottom
- [ ] [field] fr.ganfra.materialspinner.MaterialSpinner - floatingLabelBottomSpacing
- [ ] [field] fr.ganfra.materialspinner.MaterialSpinner - innerPaddingLeft
- [ ] [field] fr.ganfra.materialspinner.MaterialSpinner - errorLabelSpacing
- [ ] [field] fr.ganfra.materialspinner.MaterialSpinner - floatingLabelAnimator
- [ ] [field] fr.ganfra.materialspinner.MaterialSpinner - disabledColor
- [ ] [field] fr.ganfra.materialspinner.MaterialSpinner - extraPaddingTop
- [ ] [field] fr.ganfra.materialspinner.MaterialSpinner - floatingLabelText
- [ ] [field] fr.ganfra.materialspinner.MaterialSpinner - highlightColor
- [ ] [field] fr.ganfra.materialspinner.MaterialSpinner - arrowSize
- [ ] [field] fr.ganfra.materialspinner.MaterialSpinner - hint
- [ ] [field] fr.ganfra.materialspinner.MaterialSpinner - multiline
- [ ] [field] fr.ganfra.materialspinner.MaterialSpinner - minNbErrorLines
- [ ] [field] fr.ganfra.materialspinner.MaterialSpinner - baseColor
- [ ] [field] fr.ganfra.materialspinner.MaterialSpinner - rightLeftSpinnerPadding
- [ ] [field] fr.ganfra.materialspinner.MaterialSpinner - underlineBottomSpacing
- [ ] [method param] fr.ganfra.materialspinner.MaterialSpinner - <fr.ganfra.materialspinner.MaterialSpinner: void setEnabled(boolean)> - 0
- [ ] [method param] fr.ganfra.materialspinner.MaterialSpinner - <fr.ganfra.materialspinner.MaterialSpinner: void initAttributes(android.content.Context,android.util.AttributeSet)> - 0
- [ ] [method param] fr.ganfra.materialspinner.MaterialSpinner - <fr.ganfra.materialspinner.MaterialSpinner: void initAttributes(android.content.Context,android.util.AttributeSet)> - 1
- [ ] [method param] fr.ganfra.materialspinner.MaterialSpinner - <fr.ganfra.materialspinner.MaterialSpinner: void drawSelector(android.graphics.Canvas,int,int)> - 1
- [ ] [method param] fr.ganfra.materialspinner.MaterialSpinner - <fr.ganfra.materialspinner.MaterialSpinner: void drawSelector(android.graphics.Canvas,int,int)> - 2
- [ ] [method param] fr.ganfra.materialspinner.MaterialSpinner - <fr.ganfra.materialspinner.MaterialSpinner: void init(android.content.Context,android.util.AttributeSet)> - 0
- [ ] [method param] fr.ganfra.materialspinner.MaterialSpinner - <fr.ganfra.materialspinner.MaterialSpinner: void init(android.content.Context,android.util.AttributeSet)> - 1
- [ ] [method param] fr.ganfra.materialspinner.MaterialSpinner - <fr.ganfra.materialspinner.MaterialSpinner: void setOnItemSelectedListener(android.widget.AdapterView$OnItemSelectedListener)> - 0
- [ ] [method param] fr.ganfra.materialspinner.MaterialSpinner - <fr.ganfra.materialspinner.MaterialSpinner: int dpToPx(float)> - 0
- [ ] [method param] fr.ganfra.materialspinner.MaterialSpinner - <fr.ganfra.materialspinner.MaterialSpinner: void setPadding(int,int,int,int)> - 0
- [ ] [method param] fr.ganfra.materialspinner.MaterialSpinner - <fr.ganfra.materialspinner.MaterialSpinner: void setPadding(int,int,int,int)> - 1
- [ ] [method param] fr.ganfra.materialspinner.MaterialSpinner - <fr.ganfra.materialspinner.MaterialSpinner: void setPadding(int,int,int,int)> - 2
- [ ] [method param] fr.ganfra.materialspinner.MaterialSpinner - <fr.ganfra.materialspinner.MaterialSpinner: void setPadding(int,int,int,int)> - 3
- [ ] [field] com.nineoldandroids.animation.ValueAnimator - mValuesMap
- [ ] [field] com.nineoldandroids.animation.ValueAnimator - mUpdateListeners
- [ ] [field] com.nineoldandroids.animation.ValueAnimator - mValues
- [ ] [method param] com.nineoldandroids.animation.ValueAnimator - <com.nineoldandroids.animation.ValueAnimator: void addUpdateListener(com.nineoldandroids.animation.ValueAnimator$AnimatorUpdateListener)> - 0
- [ ] [method param] com.nineoldandroids.animation.ValueAnimator - <com.nineoldandroids.animation.ValueAnimator: void setValues(com.nineoldandroids.animation.PropertyValuesHolder- [ ] [])> - 0
- [ ] [field] fr.ganfra.materialspinner.MaterialSpinner$1 - val$listener
- [ ] [field] com.nineoldandroids.animation.ObjectAnimator - mTarget
- [ ] [method param] com.nineoldandroids.animation.ObjectAnimator - <com.nineoldandroids.animation.ObjectAnimator: com.nineoldandroids.animation.ObjectAnimator ofFloat(java.lang.Object,java.lang.String,float- [ ] [])> - 0
