### ISSUE TITLE
[Result] SMS Scheduler withtout Meta Data

### ISSUE THREAD

**Issue by omuomugin** [omuomugin/FlowDroid#12]
# SMS Scheduler withtout Meta Data

## common
- [x] [method param] com.github.yeriomin.smsscheduler.Scheduler - <com.github.yeriomin.smsscheduler.Scheduler: void schedule(com.github.yeriomin.smsscheduler.SmsModel)> - 0
- [x] [method param] com.github.yeriomin.smsscheduler.SmsSenderService - <com.github.yeriomin.smsscheduler.SmsSenderService: void sendSms(com.github.yeriomin.smsscheduler.SmsModel)> - 0
- [x] [method param] com.github.yeriomin.smsscheduler.SmsSenderService - <com.github.yeriomin.smsscheduler.SmsSenderService: void scheduleNextSms(com.github.yeriomin.smsscheduler.SmsModel)> - 0
- [x] [method return] com.github.yeriomin.smsscheduler.DbHelper - <com.github.yeriomin.smsscheduler.DbHelper: android.database.Cursor getCursor()>
- [x] [method param] com.github.yeriomin.smsscheduler.DbHelper - <com.github.yeriomin.smsscheduler.DbHelper: java.util.ArrayList getObjects(android.database.Cursor)> - 0
- [x] [method param] com.github.yeriomin.smsscheduler.DbHelper - <com.github.yeriomin.smsscheduler.DbHelper: void save(com.github.yeriomin.smsscheduler.SmsModel)> - 0
- [x] [method return] com.github.yeriomin.smsscheduler.DbHelper - <com.github.yeriomin.smsscheduler.DbHelper: java.util.ArrayList get(java.lang.String)>
- [x] [method return] com.github.yeriomin.smsscheduler.DbHelper - <com.github.yeriomin.smsscheduler.DbHelper: android.database.Cursor getCursor(java.lang.String)>
- [x] [method return] com.github.yeriomin.smsscheduler.DbHelper - <com.github.yeriomin.smsscheduler.DbHelper: com.github.yeriomin.smsscheduler.SmsModel get(long)>
- [x] [method param] com.github.yeriomin.smsscheduler.ReminderService - <com.github.yeriomin.smsscheduler.ReminderService: void remind(android.content.Context,com.github.yeriomin.smsscheduler.SmsModel)> - 1
- [x] [field] com.github.yeriomin.smsscheduler.activity.AddSmsActivity - sms
- [x] [field] com.github.yeriomin.smsscheduler.SmsModel - recurringMode
- [x] [field] com.github.yeriomin.smsscheduler.SmsModel - message
- [x] [field] com.github.yeriomin.smsscheduler.SmsModel - result
- [x] [field] com.github.yeriomin.smsscheduler.SmsModel - timestampCreated
- [x] [field] com.github.yeriomin.smsscheduler.SmsModel - recipientName
- [x] [field] com.github.yeriomin.smsscheduler.SmsModel - subscriptionId
- [x] [field] com.github.yeriomin.smsscheduler.SmsModel - recipientNumber
- [x] [field] com.github.yeriomin.smsscheduler.SmsModel - status
- [x] [method param] com.github.yeriomin.smsscheduler.SmsModel - <com.github.yeriomin.smsscheduler.SmsModel: void setRecipientNumber(java.lang.String)> - 0
- [x] [method param] com.github.yeriomin.smsscheduler.SmsModel - <com.github.yeriomin.smsscheduler.SmsModel: void setTimestampCreated(long)> - 0
- [x] [method param] com.github.yeriomin.smsscheduler.SmsModel - <com.github.yeriomin.smsscheduler.SmsModel: void setMessage(java.lang.String)> - 0
- [x] [method param] com.github.yeriomin.smsscheduler.SmsModel - <com.github.yeriomin.smsscheduler.SmsModel: void setSubscriptionId(int)> - 0
- [x] [method param] com.github.yeriomin.smsscheduler.SmsModel - <com.github.yeriomin.smsscheduler.SmsModel: void setResult(java.lang.String)> - 0
- [x] [method param] com.github.yeriomin.smsscheduler.SmsModel - <com.github.yeriomin.smsscheduler.SmsModel: void setRecipientName(java.lang.String)> - 0
- [x] [method param] com.github.yeriomin.smsscheduler.SmsModel - <com.github.yeriomin.smsscheduler.SmsModel: void setStatus(java.lang.String)> - 0
- [x] [method param] com.github.yeriomin.smsscheduler.SmsModel - <com.github.yeriomin.smsscheduler.SmsModel: void setRecurringMode(java.lang.String)> - 0
- [x] [method param] com.github.yeriomin.smsscheduler.SmsModel - <com.github.yeriomin.smsscheduler.SmsModel: void setTimestampScheduled(long)> - 0
- [x] [field] com.github.yeriomin.smsscheduler.view.BuilderSimCard$RadioOnClickListener - sms
- [x] [field] com.github.yeriomin.smsscheduler.view.Builder - sms
- [x] [method param] com.github.yeriomin.smsscheduler.view.Builder - <com.github.yeriomin.smsscheduler.view.Builder: com.github.yeriomin.smsscheduler.view.Builder setSms(com.github.yeriomin.smsscheduler.SmsModel)> - 0

## diff from with meta
- [ ] [field] com.github.yeriomin.smsscheduler.view.ContactsTask - activity
- [ ] [method param] com.github.yeriomin.smsscheduler.view.ContactsTask - <com.github.yeriomin.smsscheduler.view.ContactsTask: void setActivity(com.github.yeriomin.smsscheduler.activity.AddSmsActivity)> - 0
- [ ] [field] com.github.yeriomin.smsscheduler.view.Builder - activity
- [ ] [method param] com.github.yeriomin.smsscheduler.view.Builder - <com.github.yeriomin.smsscheduler.view.Builder: com.github.yeriomin.smsscheduler.view.Builder setActivity(com.github.yeriomin.smsscheduler.activity.AddSmsActivity)> - 0
- [ ] [field] com.github.yeriomin.smsscheduler.view.EmptinessTextWatcher - addSmsActivity
- [ ] [method param] com.github.yeriomin.smsscheduler.DbHelper - <com.github.yeriomin.smsscheduler.DbHelper: com.github.yeriomin.smsscheduler.DbHelper getDbHelper(android.content.Context)> - 0
- [ ] [method param] com.github.yeriomin.smsscheduler.DbHelper - <com.github.yeriomin.smsscheduler.DbHelper: void delete(java.lang.Long)> - 0
- [ ] [method param] com.github.yeriomin.smsscheduler.view.BuilderRecurringMode - <com.github.yeriomin.smsscheduler.view.BuilderRecurringMode: com.github.yeriomin.smsscheduler.view.Builder setActivity(com.github.yeriomin.smsscheduler.activity.AddSmsActivity)> - 0
- [ ] [field] com.github.yeriomin.smsscheduler.view.BuilderSpinner - values
