### ISSUE TITLE
[Result] Simple Todo With Meta Data

### ISSUE THREAD

**Issue by omuomugin** [omuomugin/FlowDroid#7]
# Simple Todo With Meta Data

## common
// true positive application
- [x] [method param] apps.jizzu.simpletodo.database.DBHelper - <apps.jizzu.simpletodo.database.DBHelper: void updateTaskPosition(apps.jizzu.simpletodo.model.ModelTask)> - 0
- [x] [method param] apps.jizzu.simpletodo.adapter.RecyclerViewAdapter - <apps.jizzu.simpletodo.adapter.RecyclerViewAdapter: void addTask(apps.jizzu.simpletodo.model.ModelTask,int)> - 0
- [x] [method param] apps.jizzu.simpletodo.database.TasksOrderUpdate - <apps.jizzu.simpletodo.database.TasksOrderUpdate: java.lang.Void doInBackground(apps.jizzu.simpletodo.model.ModelTask- [ ] [])> - 0

- [ ] [field] com.miguelcatalan.materialsearchview.MaterialSearchView$SavedState - query
- [ ] [field] com.miguelcatalan.materialsearchview.MaterialSearchView - mSavedState
- [ ] [method param] com.miguelcatalan.materialsearchview.MaterialSearchView - <com.miguelcatalan.materialsearchview.MaterialSearchView: void initStyle(android.util.AttributeSet,int)> - 0
- [ ] [field] hotchemi.android.rate.DialogOptions - messageText
- [ ] [field] hotchemi.android.rate.DialogOptions - neutralText
- [ ] [field] hotchemi.android.rate.DialogOptions - negativeText
- [ ] [field] hotchemi.android.rate.DialogOptions - titleText
- [ ] [field] hotchemi.android.rate.DialogOptions - positiveText
- [ ] [field] hotchemi.android.rate.AppRate - singleton
- [ ] [field] hotchemi.android.rate.AppRate - options
- [ ] [method param] hotchemi.android.rate.DialogManager - <hotchemi.android.rate.DialogManager: android.app.Dialog create(android.content.Context,hotchemi.android.rate.DialogOptions)> - 1
- [ ] [field] hotchemi.android.rate.DialogManager$1 - val$options

## diff from without meta data
// True Positive app
- [x] [method return] apps.jizzu.simpletodo.database.DBHelper - <apps.jizzu.simpletodo.database.DBHelper: apps.jizzu.simpletodo.model.ModelTask getTask(long)>
- [x] [method return] apps.jizzu.simpletodo.database.DBHelper - <apps.jizzu.simpletodo.database.DBHelper: java.util.List getAllTasks()>
- [x] [method param] apps.jizzu.simpletodo.database.DBHelper - <apps.jizzu.simpletodo.database.DBHelper: long saveTask(apps.jizzu.simpletodo.model.ModelTask)> - 0
- [x] [method return] apps.jizzu.simpletodo.database.DBHelper - <apps.jizzu.simpletodo.database.DBHelper: java.util.List getTasksForSearch(java.lang.String,java.lang.String- [ ] [],java.lang.String)>
- [x] [method param] apps.jizzu.simpletodo.alarm.AlarmHelper - <apps.jizzu.simpletodo.alarm.AlarmHelper: void setAlarm(apps.jizzu.simpletodo.model.ModelTask)> - 0
- [x] [field] apps.jizzu.simpletodo.model.ModelTask - title
- [x] [method param] apps.jizzu.simpletodo.model.ModelTask - <apps.jizzu.simpletodo.model.ModelTask: void setTitle(java.lang.String)> - 0
- [x] [field] apps.jizzu.simpletodo.adapter.RecyclerViewAdapter - mTaskList
- [x] [method param] apps.jizzu.simpletodo.adapter.RecyclerViewAdapter - <apps.jizzu.simpletodo.adapter.RecyclerViewAdapter: void addTask(apps.jizzu.simpletodo.model.ModelTask)> - 0

// False Positive app
- [ ] [field] apps.jizzu.simpletodo.model.ModelTask - date
- [ ] [method param] apps.jizzu.simpletodo.model.ModelTask - <apps.jizzu.simpletodo.model.ModelTask: void setDate(long)> - 0
- [ ] [method param] apps.jizzu.simpletodo.model.ModelTask - <apps.jizzu.simpletodo.model.ModelTask: void setId(long)> - 0

// lifecycle methods (which do not count)
- [ ] [method param] apps.jizzu.simpletodo.activity.MainActivity - <apps.jizzu.simpletodo.activity.MainActivity: void onActivityResult(int,int,android.content.Intent)> - 2
- [ ] [method param] apps.jizzu.simpletodo.activity.AddTaskActivity$onCreate$5 - <apps.jizzu.simpletodo.activity.AddTaskActivity$onCreate$5: void onClick(android.view.View)> - 0
- [ ] [method param] apps.jizzu.simpletodo.activity.AddTaskActivity$onCreate$2 - <apps.jizzu.simpletodo.activity.AddTaskActivity$onCreate$2: void onClick(android.view.View)> - 0
- [ ] [method param] apps.jizzu.simpletodo.activity.AddTaskActivity$onCreate$1 - <apps.jizzu.simpletodo.activity.AddTaskActivity$onCreate$1: void onClick(android.view.View)> - 0
- [ ] [method param] apps.jizzu.simpletodo.activity.AddTaskActivity$onCreate$4 - <apps.jizzu.simpletodo.activity.AddTaskActivity$onCreate$4: void onClick(android.view.View)> - 0
- [ ] [method param] apps.jizzu.simpletodo.activity.AddTaskActivity$onCreate$3 - <apps.jizzu.simpletodo.activity.AddTaskActivity$onCreate$3: void onClick(android.view.View)> - 0
- [ ] [method param] apps.jizzu.simpletodo.activity.EditTaskActivity$onCreate$1 - <apps.jizzu.simpletodo.activity.EditTaskActivity$onCreate$1: void onClick(android.view.View)> - 0
- [ ] [method param] apps.jizzu.simpletodo.activity.EditTaskActivity$onCreate$2 - <apps.jizzu.simpletodo.activity.EditTaskActivity$onCreate$2: void onClick(android.view.View)> - 0
- [ ] [method param] apps.jizzu.simpletodo.activity.EditTaskActivity$onCreate$3 - <apps.jizzu.simpletodo.activity.EditTaskActivity$onCreate$3: void onClick(android.view.View)> - 0
- [ ] [method param] apps.jizzu.simpletodo.activity.EditTaskActivity$onCreate$4 - <apps.jizzu.simpletodo.activity.EditTaskActivity$onCreate$4: void onClick(android.view.View)> - 0
- [ ] [method param] apps.jizzu.simpletodo.activity.EditTaskActivity$onCreate$5 - <apps.jizzu.simpletodo.activity.EditTaskActivity$onCreate$5: void onClick(android.view.View)> - 0
