### ISSUE TITLE
[Result] Simple Todo withtout Meta

### ISSUE THREAD

**Issue by omuomugin** [omuomugin/FlowDroid#8]
# Simple Todo withtout Meta

## common
// true positive application
- [x] [method param] apps.jizzu.simpletodo.database.DBHelper - <apps.jizzu.simpletodo.database.DBHelper: void updateTaskPosition(apps.jizzu.simpletodo.model.ModelTask)> - 0
- [x] [method param] apps.jizzu.simpletodo.database.TasksOrderUpdate - <apps.jizzu.simpletodo.database.TasksOrderUpdate: java.lang.Void doInBackground(apps.jizzu.simpletodo.model.ModelTask- [ ] [])> - 0
- [x] [method param] apps.jizzu.simpletodo.adapter.RecyclerViewAdapter - <apps.jizzu.simpletodo.adapter.RecyclerViewAdapter: void addTask(apps.jizzu.simpletodo.model.ModelTask,int)> - 0

// true positive third party
- [ ] [field] com.miguelcatalan.materialsearchview.MaterialSearchView$SavedState - query
- [ ] [field] com.miguelcatalan.materialsearchview.MaterialSearchView - mSavedState
- [ ] [method param] com.miguelcatalan.materialsearchview.MaterialSearchView - <com.miguelcatalan.materialsearchview.MaterialSearchView: void initStyle(android.util.AttributeSet,int)> - 0
- [ ] [field] hotchemi.android.rate.DialogOptions - messageText
- [ ] [field] hotchemi.android.rate.DialogOptions - neutralText
- [ ] [field] hotchemi.android.rate.DialogOptions - negativeText
- [ ] [field] hotchemi.android.rate.DialogOptions - titleText
- [ ] [field] hotchemi.android.rate.DialogOptions - positiveText
- [ ] [field] hotchemi.android.rate.AppRate - singleton
- [ ] [field] hotchemi.android.rate.AppRate - options
- [ ] [method param] hotchemi.android.rate.DialogManager - <hotchemi.android.rate.DialogManager: android.app.Dialog create(android.content.Context,hotchemi.android.rate.DialogOptions)> - 1
- [ ] [field] hotchemi.android.rate.DialogManager$1 - val$options
